# Generated by Django 4.0.6 on 2022-08-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_contacto_delete_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.TextField(),
        ),
    ]
