# Generated by Django 4.0.6 on 2022-08-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Publicado')], default=0)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
