# Generated by Django 4.0.6 on 2022-08-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('-fechacreado',)},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fechaDeCreacion',
            new_name='fechacreado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='pelicula_id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.post'),
            preserve_default=False,
        ),
    ]
