# Generated by Django 4.0.6 on 2022-08-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AppBlog.post'),
        ),
    ]
