# Generated by Django 4.0.6 on 2022-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_comentario_nombre_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
