# Generated by Django 4.0.6 on 2022-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_comentario_nombre_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.CharField(default='Soy simple...modificame y agrega mas info', max_length=200),
        ),
    ]
