# Generated by Django 4.0.6 on 2022-08-27 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0011_rename_perfil_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Avatar',
        ),
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
    ]
