# Generated by Django 4.0.6 on 2022-08-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_rename_avatar_perfil_rename_user_perfil_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
