# Generated by Django 4.0.6 on 2022-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0015_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.CharField(max_length=200),
        ),
    ]
