# Generated by Django 4.0.6 on 2022-09-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0023_perfil_apellido_perfil_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='nuevo_usuario', max_length=200),
        ),
    ]
